/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        love: {
          50: "#fff0f3",
          100: "#ffe0e8",
          200: "#ffc6d5",
          300: "#ff9db5",
          400: "#ff6490",
          500: "#ff2d6b",
          600: "#f0184f",
          700: "#cc0e3e",
          800: "#a81038",
          900: "#8f1235",
        },
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "bounce-gentle": "bounceGentle 2s infinite",
        "pulse-heart": "pulseHeart 1.5s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        bounceGentle: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        pulseHeart: {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.15)" },
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        jnapp: {
          primary: "#ff2d6b",
          "primary-content": "#ffffff",
          secondary: "#f471b5",
          "secondary-content": "#ffffff",
          accent: "#fb7185",
          "accent-content": "#ffffff",
          neutral: "#2a1728",
          "neutral-content": "#f5d0fe",
          "base-100": "#1a0a1f",
          "base-200": "#230d2b",
          "base-300": "#2d1238",
          "base-content": "#f5e6ff",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
        },
      },
      {
        "jnapp-aurora": {
          primary: "#5b8def",
          "primary-content": "#ffffff",
          secondary: "#818cf8",
          "secondary-content": "#ffffff",
          accent: "#67e8f9",
          "accent-content": "#0d1421",
          neutral: "#1a2740",
          "neutral-content": "#e8f0fe",
          "base-100": "#0d1421",
          "base-200": "#131c2e",
          "base-300": "#1a2740",
          "base-content": "#e8f0fe",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
        },
      },
      {
        "jnapp-sakura": {
          primary: "#e879a0",
          "primary-content": "#ffffff",
          secondary: "#c084fc",
          "secondary-content": "#ffffff",
          accent: "#fda4c4",
          "accent-content": "#1a0f1a",
          neutral: "#2d1c30",
          "neutral-content": "#fce7f3",
          "base-100": "#1a0f1a",
          "base-200": "#231525",
          "base-300": "#2d1c30",
          "base-content": "#fce7f3",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
        },
      },
      {
        "jnapp-ocean": {
          primary: "#14b8a6",
          "primary-content": "#ffffff",
          secondary: "#34d399",
          "secondary-content": "#031c1c",
          accent: "#67e8f9",
          "accent-content": "#031c1c",
          neutral: "#0d3b38",
          "neutral-content": "#ccfbf1",
          "base-100": "#031c1c",
          "base-200": "#082c2a",
          "base-300": "#0d3b38",
          "base-content": "#ccfbf1",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
        },
      },
    ],
    darkMode: false,
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
